### ISSUE TITLE
upload to chef supermarket

### ISSUE THREAD

**Issue by darwin67** [sds/chef-pyenv#8]
Could you upload this cookbook to chef supermarket?
using `github` as the source to download this cookbook doesn't seem to resolve nicely when it's nested.

**Comment by sds** [comment]
Hey @darwin67,

Would you be interested in maintaining this project? I don't use Chef anymore at my current employer and so I haven't been keeping up to date with the ecosystem. Happy to transfer ownership to you if you're interested.

**Comment by darwin67** [comment]
Hi, sure. I'm totally fine with that.
Do i just have to accept it or are there something i need to do?

**Comment by sds** [comment]
You'll need to delete your fork so I can transfer it to you.

<img width="257" alt="screen shot 2017-05-30 at 10 27 11 pm" src="https://cloud.githubusercontent.com/assets/677877/26616951/3088aeb0-4587-11e7-9d53-aeda2b6c7890.png">

**Comment by darwin67** [comment]
Okay, deleted

**Comment by darwin67** [comment]
Hey @sds , any update on this?

**Comment by sds** [comment]
Done. You just need to accept the request.

**Comment by darwin67** [comment]
got it thanks
